export const RECEIVED_TRAINING_SESSIONS = "RECEIVED_TRAINING_SESSIONS";
export const CREATED_TRAINING_SESSION = "CREATED_TRAINING_SESSION";
export const DELETED_TRAINING_SESSION = "DELETED_TRAINING_SESSION";
export const UPDATED_TRAINING_SESSION = "UPDATED_TRAINING_SESSION";
export const CREATED_TRAINING_SESSION_NOTIFICATION = "CREATED_TRAINING_SESSION_NOTIFICATION";
export const DELETED_TRAINING_SESSION_NOTIFICATION = "DELETED_TRAINING_SESSION_NOTIFICATION";
export const UPDATED_TRAINING_SESSION_NOTIFICATION = "UPDATED_TRAINING_SESSION_NOTIFICATION";