export const RECEIVED_TRAINING_SESSIONS = "RECEIVED_TRAINING_SESSIONS";
export const FETCH_TRAINING_SESSION_BY_ID = "FETCH_TRAINING_SESSION_BY_ID";
export const CREATED_TRAINING_SESSION = "CREATED_TRAINING_SESSION";
export const DELETED_TRAINING_SESSION = "DELETED_TRAINING_SESSION";