export const FETCH_TRAINING_REQUEST = "FETCH_TRAINING_REQUEST";
export const FETCH_TRAINING_SUCCESS = "FETCH_TRAINING_SUCCESS";
export const FETCH_TRAINING_FAILURE = "FETCH_TRAINING_FAILURE";
export const FETCH_DELETE_TRAINING_SESSION ="DELETE_TRAINING_SESSION";
export const FETCH_CREATE_TRAINING_SESSION ="CREATE_TRAINING_SESSION";